CompileFlags:
  Compiler: gcc
  Add: [
      # Add -isystem<directory> to fix can’t find standard library headers
      # -isystemD:/software/scoop/apps/gcc/current/x86_64-w64-mingw32/include,
      # -isystemD:/software/scoop/apps/gcc-arm-none-eabi/current/arm-none-eabi/include,
      # Add std flag
      -xc,
      -std=c99,
      # Add warning flags(-Werror)
      -Wall,
      -Wextra,
      -Wpedantic,
    ]
  Remove: []

Diagnostics:
  ClangTidy:
    Add:
      [
        clang-diagnostic-*,
        clang-analyzer-*,
        bugprone-*,
        portability-*,
        readability-*,
        misc-*,
        performance-*,
        modernize-*,
        cppcoreguidelines-*,
      ]
    Remove:
      [
        bugprone-easily-swappable-parameters,
        readability-identifier-length,
        readability-function-cognitive-complexity,
        cppcoreguidelines-macro-to-enum,
        cppcoreguidelines-avoid-magic-numbers,
        cppcoreguidelines-avoid-non-const-global-variables,
      ]
